model_name = "Base template"
description = "This is a template for building a new scoring model. All available fields are listed in this document. For documentation on what each of these fields represents, please see documentation."

[metadata]
decimal = true
ppr = false

[committed_turnovers]
fumble = 0
fumble_lost = -1
interception = -1

[passing]
yards = 0.02
yards_interval = 1
touchdown = 4

    [passing.bonuses]
    game_yardage_bonus_threshold = 300
    game_yardage_bonus = 2
    game_yardage_secondary_bonus_interval = 100
    game_yardage_secondary_bonus = 2
    td_yardage_bonus_threshold = 35
    td_yardage_bonus = 2

[receiving]
yards = 0.05
yards_interval = 1
touchdown = 6
reception = 0

    [receiving.bonuses]
    game_yardage_bonus_threshold = 100
    game_yardage_bonus = 2
    game_yardage_secondary_bonus_interval = 100
    game_yardage_secondary_bonus = 2
    td_yardage_bonus_threshold = 35
    td_yardage_bonus = 3

[rushing]
yards = 0.05
yards_interval = 1
touchdown = 6

    [rushing.bonuses]
    game_yardage_bonus_threshold = 100
    game_yardage_bonus = 2
    game_yardage_secondary_bonus_interval = 100
    game_yardage_secondary_bonus = 2
    td_yardage_bonus_threshold = 35
    td_yardage_bonus = 3

[kicking]
field_goal = 0.1
field_goal_yards = 0.1
field_goal_yards_interval = 1
field_goal_miss = -1
field_goal_miss_max_yards = 49
extra_point = 1
extra_point_miss = -1

[dst]

    [dst.defense]
    touchdown = 6
    safety = 2
    sack = 1
    fumble_recovery = 2
    interception = 2
    tackle_for_loss = 0.5
    pass_defended = 0.25
    blocked_field_goal = 3
    blocked_extra_point = 1
    blocked_punt = 2

    points_allowed = [
        {range_min = 0, range_max = 0, points = 6},
        {range_min = 1, range_max = 3, points = 4},
        {range_min = 4, range_max = 7, points = 3},
        {range_min = 8, range_max = 10, points = 2},
        {range_min = 11, range_max = 14, points = 1},
        {range_min = 15, range_max = 17, points = 0.5},
        {range_min = 18, range_max = 21, points = 0.25}
    ]
    points_allowed_deduction_threshold = 29
    points_allowed_deduction_interval = 1
    points_allowed_deduction = -0.2

    yards_allowed = [
        {range_min = 0, range_max = 100, points = 5},
        {range_min = 101, range_max = 105, points = 4},
        {range_min = 106, range_max = 110, points = 3.9},
        {range_min = 111, range_max = 115, points = 3.8},
        {range_min = 116, range_max = 120, points = 3.7},
        {range_min = 121, range_max = 125, points = 3.6},
        {range_min = 126, range_max = 130, points = 3.5},
        {range_min = 131, range_max = 135, points = 3.4},
        {range_min = 136, range_max = 140, points = 3.3},
        {range_min = 141, range_max = 145, points = 3.2},
        {range_min = 146, range_max = 150, points = 3.1},
        {range_min = 151, range_max = 155, points = 3},
        {range_min = 156, range_max = 160, points = 2.9},
        {range_min = 161, range_max = 165, points = 2.8},
        {range_min = 166, range_max = 170, points = 2.7},
        {range_min = 171, range_max = 175, points = 2.6},
        {range_min = 176, range_max = 180, points = 2.5},
        {range_min = 181, range_max = 185, points = 2.4},
        {range_min = 186, range_max = 190, points = 2.3},
        {range_min = 191, range_max = 195, points = 2.2},
        {range_min = 196, range_max = 200, points = 2.1},
        {range_min = 201, range_max = 205, points = 2},
        {range_min = 206, range_max = 210, points = 1.9},
        {range_min = 211, range_max = 215, points = 1.8},
        {range_min = 216, range_max = 220, points = 1.7},
        {range_min = 221, range_max = 225, points = 1.6},
        {range_min = 226, range_max = 230, points = 1.5},
        {range_min = 231, range_max = 235, points = 1.4},
        {range_min = 236, range_max = 240, points = 1.3},
        {range_min = 241, range_max = 245, points = 1.2},
        {range_min = 246, range_max = 250, points = 1.1},
        {range_min = 251, range_max = 255, points = 1},
        {range_min = 256, range_max = 260, points = 0.9},
        {range_min = 261, range_max = 265, points = 0.8},
        {range_min = 266, range_max = 270, points = 0.7},
        {range_min = 271, range_max = 275, points = 0.6},
        {range_min = 276, range_max = 280, points = 0.5},
        {range_min = 281, range_max = 285, points = 0.4},
        {range_min = 286, range_max = 290, points = 0.3},
        {range_min = 291, range_max = 295, points = 0.2},
        {range_min = 296, range_max = 300, points = 0.1}
    ]
    yards_allowed_deduction_threshold = 401
    yards_allowed_deduction_interval = 1
    yards_allowed_deduction = -0.02

    [dst.special_teams]
    kick_return_td = 6
    punt_return_td = 6
    extra_point_return = 2
    two_point_return = 2